### ISSUE TITLE
Can't use on Linux Mint

### ISSUE THREAD

**Issue by iuriSpinassi** [Zren/plasma-hud#10]
I don't know if is because KDE on Linux Mint is outdated, but I can't use the plasma-hud. Any tips?

**Comment by Zren** [comment]
Can you use the global menu widget? What version of Plasma does Mint __ have? [Repology](https://repology.org/project/plasma-desktop/versions) doesn't list the version for Mint.

**Comment by iuriSpinassi** [comment]
the KDE on Mint is still 5.8. I can't use the global menu... considering change my distro to manjaro.

**Comment by iuriSpinassi** [comment]
ah, and thanks for the reply!

**Comment by Zren** [comment]
It will definitely work in Manjaro KDE as that's what I'm using. Kubuntu / KDE Neon oughta work as well, but I definitely recommend Manjaro if your a gamer as it has a rolling Linux Kernel.

**Comment by iuriSpinassi** [comment]
Zren my friend! finally i installed manjaro on my PC! Your plasma-hub works perfectly.
Thank you and congratulations.
