### ISSUE TITLE
Firefox integration didn't work in Manjaro

### ISSUE THREAD

**Issue by iuriSpinassi** [Zren/plasma-hud#11]
Hi Zren!

I just installed your plasma-hud on my Manjaro yesterday and today I installed it in other PC, running Ubuntu 18.04. 

Firefox integration worked just on Ubuntu.

Any tip?

**Comment by Zren** [comment]
I personally don't use it in Firefox, so I haven't bothered trying it, but you can install `firefox-kde-opensuse`. Ubuntu and OpenSUSE patch Firefox to have global menu support, while Manjaro doesn't by default.

https://www.reddit.com/r/kde/comments/8yj8g1/how_to_use_global_menu_with_eclipse_and_firefox/

I should probably get around to installing it as well and implementing a fix for Issue #9.

**Comment by iuriSpinassi** [comment]
thanks for the reply. I will try later
