### ISSUE TITLE
Does not work on KDE Neon

### ISSUE THREAD

**Issue by DanielRios549** [Zren/plasma-hud#15]
Plasma-hud does not work on KDE Neon, i simply installed it following the steps in readme, when I run it on Konsole and press TAB, it returns these errors:
![image](https://user-images.githubusercontent.com/11152535/57901938-769f4b80-783d-11e9-8613-d35acc5a3ffa.png)

**Comment by Zren** [comment]
Konsole has a menubar, so the menu hasn't been exported to dbus.

> Either use the Global Menu widget, or add the App Menu button in to the titlebar.

**Comment by DanielRios549** [comment]
Konsole was only an example, Plasma-hud does not work at all, maybe the menu hasn't been exported to dbus in all applications or the ALT shortcut is not working properly, these errors are always printed in the terminal when I start it from there...

**Comment by Zren** [comment]
It's not exported because you're not using the "application menu" button in the titlebar (System Settings > Window Decorations > Buttons tab). I doubt you're using the global menu widget either as I still see the menu in the konsole window in your screenshot. It would be hidden if you had either of them.

https://www.youtube.com/watch?v=5Xeqhv4YSPI

**Comment by DanielRios549** [comment]
@Zren Thanks man, you are right, with "application menu" on titlebar, plasma-hud works correctly, but the problem is that there is no menubar anymore, I prefer the menubar instead of this menu in the titlebar, is there how to make it work without "application menu" in titlbebar?

**Comment by CookieAlice** [comment]
I would also like to know if it's possible to do this without having to add it to the panel and without the menu bar disappearing. @Zren

**Comment by Zren** [comment]
It's not possible to tell apps to export the menu to the OS via DBus and keep the menu in the app unfortunately. Unity achieved a workaround by showing the menu in the titlebar (locally integrated menu). I've added LIM to my window decorations:

https://github.com/Zren/material-decoration
