### ISSUE TITLE
Missing python3-psutil dependency for Kubuntu/KDE neon

### ISSUE THREAD

**Issue by kupiqu** [Zren/plasma-hud#2]
Also, I don't have unity-gtk2-modul3 and unity-gtk3-module installed, and the global menu and the HUD work just fine. I have appmenu-gtk-module-common, appmenu-gtk2-module and appmenu-gtk3-module. I think they are preferred against unity modules, but not 100% sure.

**Comment by Zren** [comment]
I left it out since I didn't encounter it during my rewrite. Oops. While it does import the python modile, it does not use it since it's only used to kill Mate's `appmenu-registrar` process.

I've removed the related code, and removed the import.

**Comment by kupiqu** [comment]
I see. Excellent, thank you!

Regarding the unity-gtk-module packages, you could add appmenu-gtk2-module and appmenu-gtk3-module as an alternative in the README...

**Comment by Zren** [comment]
I never quite understood the difference between `appmenu-*-module` and `unity-*-module`...

* https://packages.ubuntu.com/bionic/appmenu-gtk2-module
* https://packages.ubuntu.com/bionic/appmenu-gtk3-module
* https://packages.ubuntu.com/bionic/unity-gtk2-module
* https://packages.ubuntu.com/bionic/unity-gtk3-module

I think I used using unity on KDE Neon, which worked for me.

-----
## Dependencies

### apt (Kubuntu / KDE Neon)

```
sudo apt install rofi python3 python3-dbus python3-setproctitle python3-xlib gir1.2-gtk-3.0
sudo apt install appmenu-qt # Qt4
sudo apt install appmenu-gtk2-module and appmenu-gtk3-module # Gtk2 / Gtk3
# You can also use "unity-gtk2-module unity-gtk3-module"
```
Or use `unity-gtk2-module unity-gtk3-module` for Gtk2 / Gtk3.

### pacman (Arch)

```
pacman -S rofi python python-dbus python-setproctitle python-xlib gobject-introspection
pacman -S appmenu-gtk-module appmenu-qt4
```

**Comment by kupiqu** [comment]
Don't know much either, but I think one is gnome's implementation and the other is unity's. I may be wrong though...
