### ISSUE TITLE
Icon names, rather than icons, are shown in list items 

### ISSUE THREAD

**Issue by tjgordon** [Zren/plasma-hud#25]
Shown in Ksysguard, but all other applications I tested are the same, including GTK applications. 
![hud](https://user-images.githubusercontent.com/7094859/67627238-009c0900-f80d-11e9-950f-d7c803a41919.png)

I noticed this behavior right after installation, when I had copied the example config from the readme that specifies the breeze-dark icon theme to `~/.config/plasmahudrc`. I then commented out the Theme preference with #, restarted, then got the same result.

Operating System: Kubuntu 19.10
KDE Plasma Version: 5.17.1
KDE Frameworks Version: 5.62.0
Qt Version: 5.12.4
Kernel Version: 5.3.0-19-lowlatency
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-3337U CPU @ 1.80GHz
Memory: 7.7 GiB of RAM

**Comment by blueuser2** [comment]
I have this same issue. I'm running KDE neon.

**Comment by ren2r** [comment]
What version of the rofi is installed?

**Comment by Zren** [comment]
Add this to `plasmahudrc` to disable icons.

```
[Icons]
Enabled=false
```

I hadn't realized the recent version Kubuntu 19.10  didn't have this feature support, I might need to disable it by default.

* https://repology.org/project/rofi/versions
* https://github.com/davatorium/rofi/releases

Looks like it was added in 1.5.3 from June.

Yep, definitely need to disable by default. We'll see what version of rofi in in 20.04 before adding it back (same with shortcuts).

**Comment by Zren** [comment]
Or I could check rofi version and hard disable it if the version is too low.

```
$ rofi -v
Version: 1.5.4
```

**Comment by kupiqu** [comment]
This commit 39ad80b0f5d85d28cb9f7c037a08ad6bc21599d5 broke the HUD in my system:

```
Traceback (most recent call last):
  File "/usr/lib/plasma-hud/plasma-hud", line 19, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by Zren** [comment]
What distro? StackOverflow mentioned it wasn't a 1st party python library, but did mention it's used by python's setuptools which is usually preinstalled. I either need to parse the version string manually, or just not enable those features in your distro.

https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python

**Comment by kupiqu** [comment]
KDE neon User Edition

It's fine to me to keep it as far as there is an easy way to install it, which I did by installing `python3-packaging`

However I got a new error after that:

```
Traceback (most recent call last):
  File "/usr/lib/plasma-hud/plasma-hud", line 639, in <module>
    check_rofi_features()
  File "/usr/lib/plasma-hud/plasma-hud", line 252, in check_rofi_features
    p = subprocess.run(['rofi', '-version'], capture_output=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by Zren** [comment]
https://docs.python.org/3/library/subprocess.html#subprocess.run

> Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter.

https://repology.org/project/python3/versions

Hmmm, some versions of Ubuntu 18.04 only have Python 3.6, which I guess is what Neon is using.

Seems I need to use:

```python
p = subprocess.run(['rofi', '-version'], stdout=subprocess.PIPE)
```
instead. Looks like `capture_output` was added recently as a convenience function to capture both stdout and stderr.

**Comment by kupiqu** [comment]
thanks!
