### ISSUE TITLE
Use krunner in place of rofi

### ISSUE THREAD

**Issue by joaopauloalbq** [Zren/plasma-hud#3]
Thank u so much for bring HUD to Plasma 5.

An option to use krunner in place of rofi to be more native :)

![](http://3.bp.blogspot.com/-P_QZWvtN_HA/TzRcfMbNNpI/AAAAAAAAHrw/v0jav-B8_8M/s1600/appmenu-krunner.png)

https://youtu.be/9lGVy6GRbOc?t=139

**Comment by DanielRios549** [comment]
Is there some moviment to make this happen? It would be bery nice if this HUD make use of Krunner

**Comment by Zren** [comment]
This sounds like a KRunner feature request.

**[KRunner](https://zren.github.io/kde/repos/#krunner):** [GitHub](https://github.com/KDE/krunner) | [All Bugs](https://bugs.kde.org/buglist.cgi?order=bug_id%20DESC&query_format=advanced&product=krunner) | [New Bug](https://bugs.kde.org/enter_bug.cgi?product=krunner) | [Phabricator](https://phabricator.kde.org/source/krunner/) | [Pull Requests](https://phabricator.kde.org/differential/query/bGOsxqpDNf1b/#R) | [New PR (Repo: KRunner)](https://phabricator.kde.org/differential/diff/create/)

Plasma4 had https://github.com/KDE/appmenu-runner I think, but I don't believe it's been ported to Plasma5.

**Comment by joaopauloalbq** [comment]
Hum got it
I found a request for this feature here -> https://bugs.kde.org/show_bug.cgi?id=371181

**Comment by joaopauloalbq** [comment]
Artur Gaspar implemented this feature, this request can be closed.
https://github.com/ArturGaspar/krunner-appmenu
