### ISSUE TITLE
Hide DBusMenuFile Text in Entries

### ISSUE THREAD

**Issue by ihsanauliaa** [Zren/plasma-hud#34]
Hello,

I just recently started using plasma-hud when I realized that when using any JetBrains' IDE, plasma-hud shows "DBusMenuFile" for each menu entry like in the picture below:
![alt text](https://i.imgur.com/QA1oZTS.png "Plasma HUD")

Is there a way to hide those "DBusMenuFile" text? I think it happens because JetBrains' IDE are based on Java so that it doesn't really play nicely with dbusmenu etc.

Thanks in advance.

**Comment by Zren** [comment]
Add `result = result.replace('DBusMenuFile' + PATHSEPERATOR, '')` to the `format_path` function. Restart `plasma-hud`. Does it work?

https://github.com/Zren/plasma-hud/blob/master/usr/lib/plasma-hud/plasma-hud#L99

**Comment by ihsanauliaa** [comment]
It does work! But I realized that I need to replace "DBusMenuFile" with "File", "DBusMenuEdit" with "Edit" etc, rather than to hide them. I made a quick and dirty fix for this problem.

```
def format_path(path):
    #logging.debug('Path:%s', path)
    result = path.replace(PATHSEPERATOR, '', 1)
    result = result.replace('Root' + PATHSEPERATOR, '')
    result = result.replace('Label Empty' + PATHSEPERATOR, '')
    result = result.replace('_', '')
    result = result.replace('DBusMenuFile', 'File')
    result = result.replace('DBusMenuEdit', 'Edit')
    result = result.replace('DBusMenuView',  'View')
    result = result.replace('DBusMenuNavigate', 'Navigate')
    result = result.replace('DBusMenuCode', 'Code')
    result = result.replace('DBusMenuRefactor', 'Refactor')
    result = result.replace('DBusMenuRun', 'Run')
    result = result.replace('DBusMenuTools', 'Tools')
    result = result.replace('DBusMenuVCS', 'VCS')
    result = result.replace('DBusMenuWindow', 'Window')
    result = result.replace('DBusMenuHelp', 'Help')
    # return result.replace(PATHARROW, u'\u0020\u0020\u00BB\u0020\u0020')
    return result
```

I don't really know how to fix it elegantly. It will be greatly appreciated if you find another way to fix this problem.

**Comment by Zren** [comment]
How did you even export the menu to the OS? Is there a specific package I need to install?

![2020-10-08___14-49-03](https://user-images.githubusercontent.com/416367/95500904-8b6e0900-0975-11eb-9a2f-28d60b7b2d87.png)

**Comment by ihsanauliaa** [comment]
What do you mean by "export the menu to the OS"? The global menu at the top?

**Comment by Zren** [comment]
Can you still reproduce the bug? If you removed/comment out the `.replace()` calls you added in `format_path()` then restart `plasma-hud`, does it still show `DBusMenuFile` which you trigger `plasma-hud`?

How did you install GoLand? I downloaded a `GoLand-2020.2.3.tar.gz` and ran `sh ./bin/goland.sh`.

**Comment by Zren** [comment]
What I meant by export the menu is that as you can see in the screenshot, GoLand displays the menu in the application's window. Where as Konsole has the app menu button in the titlebar. When testing, the GoLand menu was not "exported" to the DBus, so the Operating System could not display the menu in the titlebar.

**Comment by ihsanauliaa** [comment]
I can't reproduce the bug at the moment because of a bug/regression in all Jetbrain's IDE that resulted in the global menu not working so that plasma-hud can't also be activated
![image](https://user-images.githubusercontent.com/45911224/95977324-efe00b00-0e42-11eb-8ee2-0438e3f5a367.png)

All Jetbrain's IDE(s) from version 2020.2.1 upwards have this regression IIRC

**Comment by Zren** [comment]
Ah that makes sense. Ping me when the bug is fixed upstream so I can test my regex code.

**Comment by ihsanauliaa** [comment]
Will do!

**Comment by louix** [comment]
The Jetbrains IDEs show the global menu for me today (well, Webstorm at least!), so I'm assuming the upstream bug is fixed. Can I help test anything?

![image](https://user-images.githubusercontent.com/28579246/153273002-78a23ff3-164b-41fa-a2c2-fd4020a619bc.png)

About exporting the menu to the OS, these packages may be required:
```
libdbusmenu-gtk3
libdbusmenu-glib
```

**Comment by Zren** [comment]
Try applying this patch: https://github.com/Zren/plasma-hud/commit/981b1fde410d0ee8a47478633d0958b8d6f9562f

**Comment by louix** [comment]
Looks like it solves it!
![image](https://user-images.githubusercontent.com/28579246/153747004-c73f2369-99b1-4249-8536-1d3837d28366.png)
