### ISSUE TITLE
Not working on specific user configuration

### ISSUE THREAD

**Issue by winiciuscota** [Zren/plasma-hud#40]
I'm getting this error when attempting to execute PlasmaHud

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/plasma-hud/plasma-hud", line 628, in hud
    appmenu_success = try_dbusmenu_interface(wm_class, kde_appmenu_service_name, kde_appmenu_object_path)
  File "/usr/lib/plasma-hud/plasma-hud", line 468, in try_dbusmenu_interface
    init_rofi()
  File "/usr/lib/plasma-hud/plasma-hud", line 312, in init_rofi
    kdeglobals = KdeGlobalsConfig()
  File "/usr/lib/plasma-hud/plasma-hud", line 229, in __init__
    super().__init__(os.path.abspath(os.path.expanduser('~/.config/kdeglobals')))
  File "/usr/lib/plasma-hud/plasma-hud", line 200, in __init__
    self.read(self.filename)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/winicius/.config/kdeglobals'
        [line 163]: 'MaximumSize[$d]\n'
```

If I create a new user and only configure PlasmaHUD everything will work, Is it possible that this is an issue on PlasmaHud? If not, is there any suggestions of how to fix it without recreating my entire configuration?

Thanks in advance.

**Comment by winiciuscota** [comment]
Removing the line 163 on the file .config/kdeglobals solved the issue

**Comment by Zren** [comment]
What group (eg: `[Colors:Button]` was `MaximumSize[$d]` in? It shouldn't error when reading `kdeglobals`. The python config reader isn't a perfect kde config reader.

**Comment by winiciuscota** [comment]
It was in the [PreviewSettings]

This was the configuration in this group:

```
[PreviewSettings]
MaximumRemoteSize=0
MaximumSize[$d]
```

**Comment by frasty** [comment]
I get a similar error:

`Gtk-Message: 01:14:55.839: Failed to load module "appmenu-gtk-module"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/plasma-hud/plasma-hud", line 628, in hud
    appmenu_success = try_dbusmenu_interface(wm_class, kde_appmenu_service_name, kde_appmenu_object_path)
  File "/usr/lib/plasma-hud/plasma-hud", line 468, in try_dbusmenu_interface
    init_rofi()
  File "/usr/lib/plasma-hud/plasma-hud", line 312, in init_rofi
    kdeglobals = KdeGlobalsConfig()
  File "/usr/lib/plasma-hud/plasma-hud", line 229, in __init__
    super().__init__(os.path.abspath(os.path.expanduser('~/.config/kdeglobals')))
  File "/usr/lib/plasma-hud/plasma-hud", line 200, in __init__
    self.read(self.filename)
  File "/usr/lib64/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.9/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/goo/.config/kdeglobals'
        [line 125]: 'ActiveColor[$d]\n'
        [line 126]: 'ActiveColor2[$d]\n'
        [line 127]: 'ActiveEffect[$d]\n'
        [line 128]: 'ActiveSemiTransparent[$d]\n'
        [line 129]: 'ActiveValue[$d]\n'
        [line 130]: 'Animated[$d]\n'
        [line 131]: 'DefaultColor[$d]\n'
        [line 132]: 'DefaultColor2[$d]\n'
        [line 133]: 'DefaultEffect[$d]\n'
        [line 134]: 'DefaultSemiTransparent[$d]\n'
        [line 135]: 'DefaultValue[$d]\n'
        [line 136]: 'DisabledColor[$d]\n'
        [line 137]: 'DisabledColor2[$d]\n'
        [line 138]: 'DisabledEffect[$d]\n'
        [line 139]: 'DisabledSemiTransparent[$d]\n'
        [line 140]: 'DisabledValue[$d]\n'
        [line 144]: 'ActiveColor[$d]\n'
        [line 145]: 'ActiveColor2[$d]\n'
        [line 146]: 'ActiveEffect[$d]\n'
        [line 147]: 'ActiveSemiTransparent[$d]\n'
        [line 148]: 'ActiveValue[$d]\n'
        [line 149]: 'Animated[$d]\n'
        [line 150]: 'DefaultColor[$d]\n'
        [line 151]: 'DefaultColor2[$d]\n'
        [line 152]: 'DefaultEffect[$d]\n'
        [line 153]: 'DefaultSemiTransparent[$d]\n'
        [line 154]: 'DefaultValue[$d]\n'
        [line 155]: 'DisabledColor[$d]\n'
        [line 156]: 'DisabledColor2[$d]\n'
        [line 157]: 'DisabledEffect[$d]\n'
        [line 158]: 'DisabledSemiTransparent[$d]\n'
        [line 159]: 'DisabledValue[$d]\n'
        [line 223]: 'ActiveColor[$d]\n'
        [line 224]: 'ActiveColor2[$d]\n'
        [line 225]: 'ActiveEffect[$d]\n'
        [line 226]: 'ActiveSemiTransparent[$d]\n'
        [line 227]: 'ActiveValue[$d]\n'
        [line 228]: 'Animated[$d]\n'
        [line 229]: 'DefaultColor[$d]\n'
        [line 230]: 'DefaultColor2[$d]\n'
        [line 231]: 'DefaultEffect[$d]\n'
        [line 232]: 'DefaultSemiTransparent[$d]\n'
        [line 233]: 'DefaultValue[$d]\n'
        [line 234]: 'DisabledColor[$d]\n'
        [line 235]: 'DisabledColor2[$d]\n'
        [line 236]: 'DisabledEffect[$d]\n'
        [line 237]: 'DisabledSemiTransparent[$d]\n'
        [line 238]: 'DisabledValue[$d]\n'
        [line 242]: 'ActiveColor[$d]\n'
        [line 243]: 'ActiveColor2[$d]\n'
        [line 244]: 'ActiveEffect[$d]\n'
        [line 245]: 'ActiveSemiTransparent[$d]\n'
        [line 246]: 'ActiveValue[$d]\n'
        [line 247]: 'Animated[$d]\n'
        [line 248]: 'DefaultColor[$d]\n'
        [line 249]: 'DefaultColor2[$d]\n'
        [line 250]: 'DefaultEffect[$d]\n'
        [line 251]: 'DefaultSemiTransparent[$d]\n'
        [line 252]: 'DefaultValue[$d]\n'
        [line 253]: 'DisabledColor[$d]\n'
        [line 254]: 'DisabledColor2[$d]\n'
        [line 255]: 'DisabledEffect[$d]\n'
        [line 256]: 'DisabledSemiTransparent[$d]\n'
        [line 257]: 'DisabledValue[$d]\n'
        [line 264]: 'ActiveColor[$d]\n'
        [line 265]: 'ActiveColor2[$d]\n'
        [line 266]: 'ActiveEffect[$d]\n'
        [line 267]: 'ActiveSemiTransparent[$d]\n'
        [line 268]: 'ActiveValue[$d]\n'
        [line 269]: 'Animated[$d]\n'
        [line 270]: 'DefaultColor[$d]\n'
        [line 271]: 'DefaultColor2[$d]\n'
        [line 272]: 'DefaultEffect[$d]\n'
        [line 273]: 'DefaultSemiTransparent[$d]\n'
        [line 274]: 'DefaultValue[$d]\n'
        [line 275]: 'DisabledColor[$d]\n'
        [line 276]: 'DisabledColor2[$d]\n'
        [line 277]: 'DisabledEffect[$d]\n'
        [line 278]: 'DisabledSemiTransparent[$d]\n'
        [line 279]: 'DisabledValue[$d]\n'
        [line 287]: 'ActiveColor[$d]\n'
        [line 288]: 'ActiveColor2[$d]\n'
        [line 289]: 'ActiveEffect[$d]\n'
        [line 290]: 'ActiveSemiTransparent[$d]\n'
        [line 291]: 'ActiveValue[$d]\n'
        [line 292]: 'Animated[$d]\n'
        [line 293]: 'DefaultColor[$d]\n'
        [line 294]: 'DefaultColor2[$d]\n'
        [line 295]: 'DefaultEffect[$d]\n'
        [line 296]: 'DefaultSemiTransparent[$d]\n'
        [line 297]: 'DefaultValue[$d]\n'
        [line 298]: 'DisabledColor[$d]\n'
        [line 299]: 'DisabledColor2[$d]\n'
        [line 300]: 'DisabledEffect[$d]\n'
        [line 301]: 'DisabledSemiTransparent[$d]\n'
        [line 302]: 'DisabledValue[$d]\n'`

I am running Plasma 5.20.90 on a Fedora 33 system

**Comment by Zren** [comment]
What the hell is writing the key, without the `=` seperator, and no value?!

**Comment by frasty** [comment]
Nevermind, I reverted to a sane kdeglobals. Probably some ancient theme configuration still hanging

**Comment by Zren** [comment]
I wrote a `try: except:` that'll use the breeze icon theme if it fails to load `~/.config/kdeglobals`.
