### ISSUE TITLE
Request: Change matching color

### ISSUE THREAD

**Issue by vdun** [Zren/plasma-hud#41]

**Comment by Zren** [comment]
* https://github.com/Zren/plasma-hud#settings
* https://github.com/Zren/plasma-hud/blob/master/usr/lib/plasma-hud/plasma-hud#L414-L417
* `man rofi | grep THEMING -A50`

**Comment by Zren** [comment]
You can now select a rofi theme with `[Style] RofiTheme=Arc-Dark`. See the readme for more details.
