### ISSUE TITLE
Colors can't be changed

### ISSUE THREAD

**Issue by alitajelsir** [Zren/plasma-hud#43]
- Colors don't change regardless of the settings. It's always beige-yellowish with gray highlighting
```
[Colors]
Background=#dee0e2
Foreground=#232629
```

- Installed from AUR
- Plasma `5.22.5`

- Sorry for the uninformative report, but I couldn't take any screenshot and I don't know which logs to provide.

**Comment by Nano-Ocelot** [comment]
- Same issue on Tumbleweed, installed from OBS. 
- Plasma 5.23.4
- Every other custom settings work like icons, font, etc., it's only the colors that won't change.

![Screenshot_20211209_015730](https://user-images.githubusercontent.com/34014750/145348845-a1c2307f-b6b1-446d-829c-f879747749ed.png)

**Comment by Zren** [comment]
[Rofi 1.7.0](https://github.com/davatorium/rofi/releases/tag/1.7.0) removed the `-color-*` parameters and now requires a `.rasi` theme. You can pass the "CSS" as a parameter too.

Here's the default CSS: https://github.com/davatorium/rofi/blame/next/doc/default_theme.rasi

mate-hud now has a custom rofi theme. It also generates `-theme-str` with the current GTK font and the colors.

* https://github.com/ubuntu-mate/mate-hud/blame/master/usr/share/rofi/themes/mate-hud.rasi
* https://github.com/ubuntu-mate/mate-hud/blame/master/usr/lib/mate-hud/mate-hud#L287

I've added a simple rofi 1.7.0 check, then generated a `-theme-str` myself that overloads a few colors in the default theme.

![2022-04-24___22-30-30](https://user-images.githubusercontent.com/416367/165011414-a1e5f437-1f5a-4bf3-946d-dd77c4593f00.png)

The dashed line is a little annoying. Gotta figure out how to change it.

**Comment by Zren** [comment]
You can now also set `[Style] RofiTheme=Arc` if you want a full fledged rofi theme. Most of the defaults are a little meh though.
