### ISSUE TITLE
plasma hud doesnt seems to look as expected

### ISSUE THREAD

**Issue by Aneeqasif** [Zren/plasma-hud#44]
https://i.imgur.com/SWgI6oV.jpg , https://i.imgur.com/vVnDnFS.jpg   i installed and then deleted xfce desktop and qt5ct and exprted its environment variable (export QT_QPA_PLATFORMTHEME=qt5ct) after hacking a lil bit i didnt like it and removed this from /etc/environment but after that both rofi and plasma hud are seemed to broken how to fix , any help for me?

**Comment by Zren** [comment]
Issue 43 is solved, and this is a duplicate.
