### ISSUE TITLE
Is appmenu-qt needed?

### ISSUE THREAD

**Issue by felagund** [Zren/plasma-hud#46]
At least on kubuntu 21.10, this package is no longer present and I could not find an obvious alternative. But PlasmaHUD still works with qt apps (at leaste Kate and Konsole), so I guess it is not needed?

**Comment by Zren** [comment]
It's got Qt 4 dependencies, so It's required for Qt4 apps like... Clementine? Not sure.

* 18.04 https://packages.ubuntu.com/en/bionic/appmenu-qt
* 20.04 https://packages.ubuntu.com/en/focal/appmenu-qt (HTTP 404)

In any case, if the app displays fine in the global menu panel widget then it's not necessary. I'll update the ReadMe.
